src/Entity/Partie.php
<?php
/**
 * Created by PhpStorm.
 * User2: Nicolas
 * Date: 20/02/2018
 * Time: 10:23
 */

namespace App\Entity;


use Doctrine\ORM\Mapping as ORM;


/**
 * Class partie
 * @package App\Entity
 * @ORM\Entity(repositoryClass="App\Repository\PartieRepository")
 */
class Partie
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     * @ORM\Column(type="integer")
     * @var integer
     */
    private $id;

    /**
     * @ORM\Column(type="text")
     */
    private $main_j1; // text --> tableau JSON
    /**

    /**
     * @ORM\Column(type="text")
     */
    private $main_j2; // text --> tableau JSON

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User")
     */
    private $j1; // liaison

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User")
     */
    private $j2; // liaison

    /**
     * @ORM\Column(type="integer")
     * @var integer
     */
    private $score_j1; // int

    /**
     * @ORM\Column(type="integer")
     * @var integer
     */
    private $score_j2; // int

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User");
     */
    private $tour; // "J1 ou J2" OU liaison

    /**
     * @ORM\Column(type="integer")
     */
    private $manche; // int

    /**
     * @ORM\Column(type="text")
     */
    private $pioche; // text --> tableau avec cartes restantes

    /**
     * @ORM\Column(type="text")
     */
    private $objectifs; // text --> tableau [id_objectif : id_joueur]

    /**
     * @ORM\Column(type="text")
     */
    private $carte_jetee; // text --> id de la carte

    /**
     * @ORM\Column(type="text")
     */
    private $action_j1; // tableau JSON

    /**
     * @ORM\Column(type="text")
     */
    private $action_j2; // tableau JSON

    /**
     * @ORM\Column(type="text")
     */
    private $terrain_j1; // tableau JSON

    /**
     * @ORM\Column(type="text")
     */
    private $terrain_j2;

    /**
     * @ORM\Column(type="smallint")
     */
    private $etat;


    /**
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param int $id
     */
    public function setId($id)
    {
        $this->id = $id;
    }

    /**
     * @return mixed
     */
    public function getPartieNom()
    {
        return $this->partie_nom;
    }

    /**
     * @param mixed $partie_nom
     */
    public function setPartieNom($partie_nom)
    {
        $this->partie_nom = $partie_nom;
    }

    /**
     * @return mixed
     */
    public function getMainJ1()
    {
        return (array)json_decode($this->main_j1);
    }

    /**
     * @param mixed $main_j1
     */
    public function setMainJ1($main_j1)
    {
        $this->main_j1 = $main_j1;
    }

    /**
     * @return mixed
     */
    public function getMainJ2()
    {
        return (array)json_decode($this->main_j2)   ;
    }

    /**
     * @param mixed $main_j2
     */
    public function setMainJ2($main_j2)
    {
        $this->main_j2 = $main_j2;
    }

    /**
     * @return mixed
     */
    public function getJ1()
    {
        return $this->j1;
    }

    /**
     * @param mixed $j1
     */
    public function setJ1($j1)
    {
        $this->j1 = $j1;
    }

    /**
     * @return mixed
     */
    public function getJ2()
    {
        return $this->j2;
    }

    /**
     * @param mixed $j2
     */
    public function setJ2($j2)
    {
        $this->j2 = $j2;
    }

    /**
     * @return int
     */
    public function getScoreJ1()
    {
        return $this->score_j1;
    }

    /**
     * @param int $score_j1
     */
    public function setScoreJ1($score_j1)
    {
        $this->score_j1 = $score_j1;
    }

    /**
     * @return int
     */
    public function getScoreJ2()
    {
        return $this->score_j2;
    }

    /**
     * @param int $score_j2
     */
    public function setScoreJ2($score_j2)
    {
        $this->score_j2 = $score_j2;
    }

    /**
     * @return mixed
     */
    public function getTour()
    {
        return $this->tour;
    }

    /**
     * @param mixed $tour
     */
    public function setTour($tour)
    {
        $this->tour = $tour;
    }

    /**
     * @return mixed
     */
    public function getManche()
    {
        return $this->manche;
    }

    /**
     * @param mixed $manche
     */
    public function setManche($manche)
    {
        $this->manche = $manche;
    }

    /**
     * @return mixed
     */
    public function getPioche()
    {
        return json_decode($this->pioche);
    }

    /**
     * @param mixed $pioche
     */
    public function setPioche($pioche)
    {
        $this->pioche = $pioche;
    }

    /**
     * @return mixed
     */
    public function getObjectifs()
    {
        return (array)json_decode($this->objectifs);
    }

    /**
     * @param mixed $objectifs
     */
    public function setObjectifs($objectifs)
    {
        $this->objectifs = $objectifs;
    }

    /**
     * @return mixed
     */
    public function getCarteJetee()
    {
        return $this->carte_jetee;
    }

    /**
     * @param mixed $carte_jetee
     */
    public function setCarteJetee($carte_jetee)
    {
        $this->carte_jetee = $carte_jetee;
    }

    /**
     * @return mixed
     */
    public function getActionJ1()
    {
        return (array)json_decode($this->action_j1);
    }

    /**
     * @param mixed $action_j1
     */
    public function setActionJ1($action_j1)
    {
        $this->action_j1 = $action_j1;
    }

    /**
     * @return mixed
     */
    public function getActionJ2()
    {
        return (array)json_decode($this->action_j2);
    }

    /**
     * @param mixed $action_j2
     */
    public function setActionJ2($action_j2)
    {
        $this->action_j2 = $action_j2;
    }

    /**
     * @return mixed
     */
    public function getTerrainJ1()
    {
        return json_decode($this->terrain_j1);
    }

    /**
     * @param mixed $terrain_j1
     */
    public function setTerrainJ1($terrain_j1)
    {
        $this->terrain_j1 = $terrain_j1;
    }

    /**
     * @return mixed
     */
    public function getTerrainJ2()
    {
        return json_decode($this->terrain_j2);
    }

    /**
     * @param mixed $terrain_j2
     */
    public function setTerrainJ2($terrain_j2)
    {
        $this->terrain_j2 = $terrain_j2;
    }

    /**
     * @return mixed
     */
    public function getEtat()
    {
        return $this->etat;
    }

    /**
     * @param mixed $etat
     */
    public function setEtat($etat)
    {
        $this->etat = $etat;
    }




}

src/Controller/PartieController.php
<?php

namespace App\Controller;


use App\Entity\Carte;
use App\Entity\Objectif;
use App\Entity\Partie;
use App\Entity\User;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/partie")
 * Class PartieController
 * @package App\Controller
 */

class PartieController extends Controller
{
    /**
     * @Route("/recherche", name="recherche_joueurs")
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function rechercheJoueurs()
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');
        $userId = $this->getUser()->getId();
        $joueurs = $this->getDoctrine()->getRepository(User::class)->findAll();
        return $this->render('partie/recherche.html.twig', ['joueurs' => $joueurs]);
    }

    /**
     *
     * /**
     * @Route("/creer", name="creer_partie")
     * @param Request $request
     * @return Response
     */
    public function creerPartie(Request $request)
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');
        $idAdversaire = $request->request->get('adversaire');
        $idJoueur = $this->getUser()->getId();
        $joueur = $this->getDoctrine()->getRepository(User::class)->find($idJoueur);
        $adversaire = $this->getDoctrine()->getRepository(User::class)->find($idAdversaire);
        $objectifs = $this->getDoctrine()->getRepository(Objectif::class)->findAll();
        $cartes = $this->getDoctrine()->getRepository(Carte::class)->findAll();


        $partie = new Partie();

        $tCartes = array();
        $tObjectifs = array();
        $tActions = array();

        foreach($objectifs as $objectif) {
            $tObjectifs["obj".$objectif->getId()] =  0;
        }

        foreach($cartes as $carte) {
            $tCartes[] = $carte->getId();
        }



        $secret = array('etat' => 0, 'carte' => 0);
        $diss = array('etat' => 0, 'cartes' => array());
        $cadeau = array('etat' => 0, 'cartes' => array());
        $concurrence = array('etat' => 0, 'cartes' => array("paire1" => array(), "paire2" => array()));
        $tActions = array('secret' => $secret, 'dissimulation' => $diss, 'cadeau' => $cadeau, 'concurrence' => $concurrence);

        shuffle($tCartes);

        $cartejetee = array_pop($tCartes);


        $tMainJ1 = array();
        for($i=0; $i<6; $i++) {
            $tMainJ1[] = array_pop($tCartes);
        }
        $tMainJ2 = array();
        for($i=0; $i<6; $i++) {
            $tMainJ2[] = array_pop($tCartes);
        }


        $random = rand(1,2);

        if($random == 1) {
            $partie->setTour($joueur);
            $tMainJ1[] = array_pop($tCartes);
        } else {
            $partie->setTour($adversaire);
            $tMainJ2[] = array_pop($tCartes);
        }

        sort($tMainJ1);
        sort($tMainJ2);

        $terrainJ1 = array();
        $terrainJ2 = array();

        $pioche = $tCartes;

        $partie->setJ1($joueur);
        $partie->setJ2($adversaire);
        $joueur->setPartiesJouees($joueur->getPartiesJouees() + 1);
        $adversaire->setPartiesJouees($adversaire->getPartiesJouees() + 1);
        $partie->setMainJ1(json_encode($tMainJ1));
        $partie->setMainJ2(json_encode($tMainJ2));
        $partie->setPioche(json_encode($pioche));
        $partie->setScoreJ1(0);
        $partie->setEtat(0);
        $partie->setScoreJ2(0);
        $partie->setManche(1);
        $joueur->setPartiesJouees($joueur->getPartiesJouees() + 1 );
        $adversaire->setPartiesJouees($adversaire->getPartiesJouees() +1);
        $partie->setObjectifs(json_encode($tObjectifs));
        $partie->setCarteJetee($cartejetee);
        $partie->setActionJ1(json_encode($tActions));
        $partie->setActionJ2(json_encode($tActions));
        $partie->setTerrainJ1(json_encode($terrainJ1));
        $partie->setTerrainJ2(json_encode($terrainJ2));

        $em = $this->getDoctrine()->getManager();

        $em->persist($partie);
        $em->flush();

        return $this->redirectToRoute("afficher_partie", ['id' => $partie->getId(), 'partie' => $partie]);
    }

    /**
     * @Route("/{id}", name="afficher_partie")
     * @param Partie $partie
     */
    public function afficherPartie(Partie $partie) {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');
        $cartes = $this->getDoctrine()->getRepository("App:Carte")->findAll();
        $objectifs = $this->getDoctrine()->getRepository("App:Objectif")->findAll();

        $joueur = $this->getUser();
        $adversaire = ($joueur == $partie->getJ1()) ? $partie->getJ2() : (($joueur == $partie->getJ2()) ? $partie->getJ1() : 'Erreur');
        $tActionsA = ($adversaire == $partie->getJ1()) ? $partie->getActionJ1() : (($adversaire == $partie->getJ2()) ? $partie->getActionJ2() : 'Erreur');
        $tActionsJ = ($joueur == $partie->getJ1()) ? $partie->getActionJ1() : (($joueur == $partie->getJ2()) ? $partie->getActionJ2() : 'Erreur');

        $actionsJ = array_column($tActionsJ, 'etat');
        $actionsA = array_column($tActionsA, 'etat');

        $tCartes = array();
        foreach($cartes as $carte) {
            $tCartes[$carte->getId()] = $carte;
        }


        return $this->render('Partie/afficher.html.twig', ['partie' => $partie, 'cartes' => $tCartes, 'objectifs' => $objectifs, 'id' => $partie, 'actionsJ' => $actionsJ, 'actionsA' => $actionsA]);
    }

    /**
     * @Route("/{id}/tour_suivant", name="tour_suivant")
     */
    public function tourSuivant(Partie $partie)
    {
        $joueur = $this->getUser();
        $adversaire =  ($joueur == $partie->getJ1()) ? $partie->getJ2() : (($joueur == $partie->getJ2()) ?  $partie->getJ1() : 'Erreur');

        $tMainJ1 = $partie->getMainJ1();
        $tMainJ2 = $partie->getMainJ2();
        $pioche = $partie->getPioche();
        $actionsJ1 = $partie->getActionJ1();
        $actionsJ2 = $partie->getActionJ2();

        $cartePioche = array_pop($pioche);


        if ($joueur == $partie->getJ1()) {
            $tMainJ2[] = $cartePioche;
            sort($tMainJ2);
            $partie->setMainJ2(json_encode($tMainJ2));
        } else {
            if ($joueur == $partie->getJ2()) {
                $tMainJ1[] = $cartePioche;
                sort($tMainJ1);
                $partie->setMainJ1(json_encode($tMainJ1));
            }
        }

        $partie->setPioche(json_encode($pioche));

        if($partie->getTour() == $joueur) {
            $partie->setTour($adversaire);
        }
        else if($partie->getTour() == $adversaire) {
            $partie->setTour($joueur);
        }

        $this->getDoctrine()->getManager()->flush();

        return $this->redirectToRoute('afficher_partie', ['partie' => $partie, 'id' => $partie->getId()]);
    }

    /**
     * @Route("/{id}/secret", name="secret")
     */
    public function secret(Partie $partie, Request $request)
    {
        $joueur = $this->getUser();

        $carteSecretId = $request->request->get('secret');
        $tMain =  ($joueur == $partie->getJ1()) ? $partie->getMainJ1() : (($joueur == $partie->getJ2()) ? $partie->getMainJ2() : 'Erreur');
        $tActions = ($joueur == $partie->getJ1()) ? $partie->getActionJ1() : (($joueur == $partie->getJ2()) ? $partie->getActionJ2() : 'Erreur');
        unset($tMain[array_search($carteSecretId, $tMain)]);
        $ntMain = array_values($tMain);
        sort($ntMain);
        $tActions['secret']->etat = 1;
        ($joueur == $partie->getJ1()) ? $partie->setMainJ1(json_encode($ntMain)) : (($joueur == $partie->getJ2()) ? $partie->setMainJ2(json_encode($ntMain)) : 'Erreur');
        ($joueur == $partie->getJ1()) ? $partie->setActionJ1(json_encode($tActions)) : (($joueur == $partie->getJ2()) ? $partie->setActionJ2(json_encode($tActions)) : 'Erreur');
        $this->tourSuivant($partie);
        $this->getDoctrine()->getManager()->flush();
        return $this->redirectToRoute('afficher_partie', ['partie' => $partie, 'id' => $partie->getId()]);
    }

    /**
     * @Route("/{id}/dissimulation", name="dissimulation")
     * @param Partie $partie
     * @param Request $request
     */
    public function dissimulation(Partie $partie, Request $request)
    {
        $joueur = $this->getUser();
        $adversaire = ($joueur == $partie->getJ1()) ? $partie->getJ2() : ($joueur == $partie->getJ2()) ? $partie->getJ1() : 'Erreur';
        $carteDissId1 = $request->request->get('carte1');
        $carteDissId2 = $request->request->get('carte2');
        $carteDiss1 = $this->getDoctrine()->getRepository(Carte::class)->find($carteDissId1);
        $carteDiss2 = $this->getDoctrine()->getRepository(Carte::class)->find($carteDissId2);
        $tMain = ($joueur == $partie->getJ1()) ? $partie->getMainJ1() : (($joueur == $partie->getJ2(
            )) ? $partie->getMainJ2() : 'Erreur');
        $tActions = ($joueur == $partie->getJ1()) ? $partie->getActionJ1() : (($joueur == $partie->getJ2(
            )) ? $partie->getActionJ2() : 'Erreur');

        if ($carteDissId1 == null || $carteDissId2 == null) {
            return $this->redirectToRoute('afficher_partie', ['partie' => $partie, 'id' => $partie->getId()]);
        } else {
            unset($tMain[array_search($carteDissId1, $tMain)]);
            unset($tMain[array_search($carteDissId2, $tMain)]);

            $ntMain = array_values($tMain);

            sort($ntMain);

            $tActions['dissimulation']->etat = 1;
            $tActions['dissimulation']->cartes = array($carteDissId1, $carteDissId2);

            ($joueur == $partie->getJ1()) ? $partie->setMainJ1(json_encode($ntMain)) : (($joueur == $partie->getJ2(
                )) ? $partie->setMainJ2(json_encode($ntMain)) : 'Erreur');

templates/Partie/afficher.html.twig
{% extends 'base2.html.twig' %}

{% block body %}


    {{ include('Partie/plateau.html.twig') }}
f
{% endblock %}

{% block javascripts %}
    <script
            src="https://code.jquery.com/jquery-3.3.1.js"
            integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
            crossorigin="anonymous"></script>
    <script>


        $(document).ready(function() {
            $('.oui1').animate({left: "12%", top: "85%"}, 500, function () {
                $('.face1').animate({zIndex: "6", opacity: "1"}, 200)
            });
            $('.oui2').animate({left: "23%", top: "85%"}, 500, function () {
                $('.face2').animate({zIndex: "6", opacity: "1"}, 215)
            });
            $('.oui3').animate({left: "34%", top: "85%"}, 500, function () {
                $('.face3').animate({zIndex: "6", opacity: "1"}, 230)
            });
            $('.oui4').animate({left: "45%", top: "85%"}, 500, function () {
                $('.face4').animate({zIndex: "6", opacity: "1"}, 245)
            });
            $('.oui5').animate({left: "56%", top: "85%"}, 500, function () {
                $('.face5').animate({zIndex: "6", opacity: "1"}, 260)
            });
            $('.oui6').animate({left: "67%", top: "85%"}, 500, function () {
                $('.face6').animate({zIndex: "6", opacity: "1"}, 275)
            });
            $('.oui7').animate({left: "78%", top: "85%"}, 500, function () {
                $('.face7').animate({zIndex: "6", opacity: "1"}, 290)
            });


            $('#secret').click(function () {
                $('.bienvenue').fadeOut(function () {
                    $('.bienvenue').empty().load('{{ path('afficher_actions', {'id' : partie.id}) }} #secret', function () {
                        $('.bienvenue').fadeIn('slow');
                    })
                })
            });

            $('#dissimulation').click(function () {
                $('.bienvenue').fadeOut(function () {
                    $('.bienvenue').empty().load('{{ path('afficher_actions', {'id' : partie.id}) }} #dissimulation', function () {
                        $('.bienvenue').fadeIn('slow');
                    })
                })
            });

            $('#cadeau').click(function () {
                $('.bienvenue').fadeOut(function () {
                    $('.bienvenue').empty().load('{{ path('afficher_actions', {'id' : partie.id}) }} #cadeau', function () {
                        $('.bienvenue').fadeIn('slow');
                    })
                })
            });

            $('#concurrence').click(function () {
                $('.bienvenue').fadeOut(function () {
                    $('.bienvenue').empty().load('{{ path('afficher_actions', {'id' : partie.id}) }} #concurrence', function () {
                        $('.bienvenue').fadeIn('slow');
                    })
                })
            });

            $('.annuler').click(function () {
                console.log('Test');
            });

            {% if actionsJ[0] == 1 and actionsJ[1] == 1 and actionsJ[2] == 2 and actionsJ[3] == 2 and actionsA[0] == 1 and actionsA[1] == 1 and actionsA[2] == 2 and actionsA[3] == 2 %}
            $('.bienvenue').fadeOut(function () {
                $('.bienvenue').empty().load('{{ path('afficher_actions', {'id' : partie.id}) }} #finmanche', function () {
                    $('.bienvenue').fadeIn('slow');
                })
            })
            {% endif %}

            {% if app.user.id == partie.J2.id %}
            {% if partie.actionJ1['concurrence'].etat == 1 %}
            $('.bienvenue').fadeOut(function () {
                $('.bienvenue').empty().load('{{ path('afficher_actions', {'id' : partie.id}) }} #concurrenceA', function () {
                    $('.bienvenue').fadeIn('slow');
                })
            })
            {% endif %}

            {% if partie.actionJ1['cadeau'].etat == 1 %}
            $('.bienvenue').fadeOut(function () {
                $('.bienvenue').empty().load('{{ path('afficher_actions', {'id' : partie.id}) }} #cadeauA', function () {
                    $('.bienvenue').fadeIn('slow');
                })
            })
            {% endif %}
            {% endif %}

            {% if app.user.id == partie.J1.id %}

            {% if partie.actionJ2['concurrence'].etat == 1 %}
            $('.bienvenue').fadeOut(function () {
                $('.bienvenue').empty().load('{{ path('afficher_actions', {'id' : partie.id}) }} #concurrenceA', function () {
                    $('.bienvenue').fadeIn('slow');
                })
            })
            {% endif %}

            {% if partie.actionJ2['cadeau'].etat == 1 %}
            $('.bienvenue').fadeOut(function () {
                $('.bienvenue').empty().load('{{ path('afficher_actions', {'id' : partie.id}) }} #cadeauA', function () {
                    $('.bienvenue').fadeIn('slow');
                })
            })
            {% endif %}


            {% endif %}

        });


    </script>
{% endblock %}

templates/Partie/attente.html.twig
{% extends 'base.html.twig' %}
{% block style %}
    <style>
        html, body {
            height: 100%;
            margin: 0;
        }

        #snake {
            display: flex;
            align-items: center;
            justify-content: center;
        }
        canvas {
            background: black;
            border: 1px solid white;
        }
    </style>
{% endblock %}

{% block body %}


    <div id="snake"><canvas width="400" height="400" id="game"></canvas></div>
{% endblock %}

{% block javascripts %}
    <script>
        var canvas = document.getElementById('game');
        var context = canvas.getContext('2d');

        var grid = 16;
        var snake = {
            x: 160,
            y: 160,
            dx: grid,
            dy: 0,
            cells: [],
            maxCells: 4
        };
        var count = 0;
        var apple = {
            x: 320,
            y: 320
        };

        function getRandomInt(min, max) {
            return Math.floor(Math.random() * (max - min)) + min;
        }

        // game loop
        function loop() {
            requestAnimationFrame(loop);

            // slow game loop to 15 fps instead of 60 - 60/15 = 4
            if (++count < 4) {
                return;
            }

            count = 0;
            context.clearRect(0,0,canvas.width,canvas.height);

            snake.x += snake.dx;
            snake.y += snake.dy;

            // wrap snake position on edge of screen
            if (snake.x < 0) {
                snake.x = canvas.width - grid;
            }
            else if (snake.x >= canvas.width) {
                snake.x = 0;
            }

            if (snake.y < 0) {
                snake.y = canvas.height - grid;
            }
            else if (snake.y >= canvas.height) {
                snake.y = 0;
            }

            // keep track of where snake has been. front of the array is always the head
            snake.cells.unshift({x: snake.x, y: snake.y});

            // remove cells as we move away from them
            if (snake.cells.length > snake.maxCells) {
                snake.cells.pop();
            }

            // draw apple
            context.fillStyle = '#8e44ad';
            context.fillRect(apple.x, apple.y, grid-1, grid-1);

            // draw snake
            context.fillStyle = '#ffc107';
            snake.cells.forEach(function(cell, index) {
                context.fillRect(cell.x, cell.y, grid-1, grid-1);

                // snake ate apple
                if (cell.x === apple.x && cell.y === apple.y) {
                    snake.maxCells++;

                    apple.x = getRandomInt(0, 25) * grid;
                    apple.y = getRandomInt(0, 25) * grid;
                }

                // check collision with all cells after this one (modified bubble sort)
                for (var i = index + 1; i < snake.cells.length; i++) {

                    // collision. reset game
                    if (cell.x === snake.cells[i].x && cell.y === snake.cells[i].y) {
                        snake.x = 160;
                        snake.y = 160;
                        snake.cells = [];
                        snake.maxCells = 4;
                        snake.dx = grid;
                        snake.dy = 0;

                        apple.x = getRandomInt(0, 25) * grid;
                        apple.y = getRandomInt(0, 25) * grid;
                    }
                }
            });
        }

        document.addEventListener('keydown', function(e) {
            // prevent snake from backtracking on itself
            if (e.which === 37 && snake.dx === 0) {
                snake.dx = -grid;
                snake.dy = 0;
            }
            else if (e.which === 38 && snake.dy === 0) {
                snake.dy = -grid;
                snake.dx = 0;
            }
            else if (e.which === 39 && snake.dx === 0) {
                snake.dx = grid;
                snake.dy = 0;
            }
            else if (e.which === 40 && snake.dy === 0) {
                snake.dy = grid;
                snake.dx = 0;
            }
        });

        requestAnimationFrame(loop);
    </script>
{% endblock %}

templates/Partie/finmanche.html.twig
{% extends 'base.html.twig' %}
{% block body %}
<section class="main-contenu">
    <div class="logo">
        <div class="image">
            <img src="img/logo.svg" alt="logo A la conquête du Graal">
        </div>
        <div class="titre">
            <h1>
                Manche terminée
            </h1>
        </div>
    </div>
</section>
<section class="jouer col-md-10" style="margin-left:auto; margin-right:auto; margin-top:15px;">
    <div class="bouton1 col-md-10">
        <p style="color:white; margin-top:15px;">
            Le score pour gagner n'est pas atteint par l'un des deux joueurs, vous devez donc rejouer une nouvelle manche.
        </p>
        <h2>
            <div class="link-one">
                <p>
                    <!-- Nom joueur -->
                    {{ partie.j1.pseudo }}

                    <!-- Score -->
                    {{ partie.scoreJ1 }}
                </p>
                <p>
                    <!-- Nom joueur -->
                    {{ partie.j2.pseudo }}

                    <!-- Score -->
                    {{ partie.scoreJ2 }}
                </p>
            </div>
        </h2>
        <button class="nv-tour">
            <a href="{{ path('afficher_partie', {'id': partie.id}) }}"></a>
        </button>
    </div>

</section>

{% endblock %}